name: demo
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Generate build
      run: npm ci && npm run build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: demo
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main